FROM karluqs/graylog:3.0.2-2

ENV GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200 \
    GRAYLOG_PASSWORD_SECRET=somepasswordpepper \
    # Password: admin
    GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918 \
    GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/ \
    GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog

EXPOSE 9000 514 514/udp 12201 12201/udp 12202/udp 12203/udp 12204/udp

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["graylog"]
