FROM docker.elastic.co/elasticsearch/elasticsearch:6.8.1

ENV discovery.type=single-node \
    http.port=9200 \
    http.cors.enabled=true \
    http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization \
    http.cors.allow-credentials=true

EXPOSE 9200 9300

VOLUME ["/usr/share/elasticsearch/data"]

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

CMD ["eswrapper"]